# Generated by Django 5.0.7 on 2024-10-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.community'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='!gMathg1zEVW6DrlWqAloiy2sfCtOX38tsVlbX0Fn', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('CO', 'Community Owner'), ('MM', 'Community Member'), ('CC', 'Community Customer')], max_length=50, null=True),
        ),
    ]
