# Generated by Django 5.0.7 on 2024-09-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='!0IORbDou2UaayCJN2tubFWDIxMzg0BbdpUBm6tY9', max_length=128),
        ),
    ]
