# Generated by Django 5.0.7 on 2024-10-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_community_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('add_user_group', 'Can add User to Group'), ('delete_user_group', 'Can delete the User Group'), ('add_user_permissions', 'Can add the User permissions'), ('get_user_permissions', 'Can get the User permissions')]},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='!dniZSmA1j5jEHslFSHpNo0kuGsMLZs0WR4FlFqMF', max_length=128),
        ),
    ]
