# Generated by Django 5.0.7 on 2024-09-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_community_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='!URXIwVgsKgkdhvTJ7EhN4p8a3pMIQGZZZicDuzS7', max_length=128),
        ),
    ]
