# Generated by Django 5.0.7 on 2024-10-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_options_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='!mGvkzUAa1ONvuQr5WxjE9MpQyKNFHpx8DPvx5lWq', max_length=128),
        ),
    ]
