# Generated by Django 5.0.7 on 2024-10-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='!gDLA79pLIMAxmQEAAfcAusKPbTscnSwG07uh9cyZ', max_length=128),
        ),
    ]
