# Generated by Django 5.0.7 on 2024-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_modify_datetime_block_modified_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='account.block'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='account.flat'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='!awW6V1ggkUkqs4WERIJV3AnAyl0XRC7kWHg5oQJy', max_length=128),
        ),
    ]
