# Generated by Django 5.0.7 on 2024-11-03 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_userprofile_user_type_userprofile_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='flats',
        ),
        migrations.AlterField(
            model_name='flat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='!FYeNhO1zEahljetY2lJtd8AN46R8nKuR8iR7GXUD', max_length=128),
        ),
    ]
