# Generated by Django 5.0.7 on 2024-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_community_latitude_community_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='!atz2doH3Yo1HfggMrkXYg7fJCrcRMKibQYrdcoDT', max_length=128),
        ),
    ]
