version: "3.12"

services:
  web:
    build: .
    container_name: waterMeter_container
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always # Ensure the container restarts automatically
