# Generated by Django 5.0.7 on 2024-10-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watermeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterconsumption',
            options={'permissions': [('scan_meter', 'Can scan the meter to get Readings')]},
        ),
    ]
